package com.arilsondev.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
@DynamoDBTable(tableName = "payment")
public class Payment implements Serializable{

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String paymentId;

    @DynamoDBAttribute
    private String orderId;

    @DynamoDBAttribute
    private Integer costumerId;

    @DynamoDBAttribute
    private Integer sellerId;

    @DynamoDBAttribute
    private String paymentMethod;

    @DynamoDBAttribute
    private String paymentStatus;

    @DynamoDBAttribute
    private String paymentStatusNotes;
}
